version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: STRONG_ROOT_PASSWORD
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: STRONG_USER_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
