version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: jf98hfr392z7guhUHFUZTGJDEiuzfg7ghr83478hIghfnihdfhugguZguGug22837
      MYSQL_DATABASE: redstack
      MYSQL_USER: mcadmin
      MYSQL_PASSWORD: gHG6jfz2h7zGHUh7383hgUZGihiuhoiu
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
